################################################################################
# \ \   / (_)_ __| |_ _   _  __ _| | |  \/  | __ _  ___| |__ (_)_ __   ___
#  \ \ / /| | '__| __| | | |/ _` | | | |\/| |/ _` |/ __| '_ \| | '_ \ / _ \
#   \ V / | | |  | |_| |_| | (_| | | | |  | | (_| | (__| | | | | | | |  __/
#    \_/  |_|_|   \__|\__,_|\__,_|_| |_|  |_|\__,_|\___|_| |_|_|_| |_|\___|
###############################################################################
virtualMachine:
  name: desktop
  namespace: default
  runStrategy: "Always"
  features:
    kvm:
      enabled: true
      hidden: false
    hyperv: false
    acpiEnabled: true
    autoattachPodInterface: true
    autoattachSerialConsole: true
    autoattachGraphicsDevice: true
    networkInterfaceMultiqueue: true
  clock:
    enabled: true
    timezone: utc
    hpet:
      enabled: true
      present: false
    pit:
      enabled: true
      tickPolicy: delay
    rtc:
      enabled: true
      tickPolicy: catchup
    kvm: true
    hyperv: false
  firmware:
    smmEnabled: false
    efi:
      enabled: true
      secureBoot: false
    uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
  machine:
    priorityClassName: system-node-critical
    instancetype:
      enabled: false
      name: standard-small
      kind: virtualMachineClusterInstancetype
    architecture: amd64
    machineType: q35
    cpuModel: host-passthrough
    sockets: 1
    vCores: 2
    threads: 1
    pinCores: true
    emulatorThread: false
    memory:
      base: 4Gi
      overcommit:
        enabled: false
        limit: 4Gi
        overhead: false
  gpus: []
  interfaces:
    - masquerade: {}
      name: default
      model: virtio
  networks:
    - name: default
      pod: {}
virtualMachinePool:
  enabled: false
  replicas: 3
  hpa:
    enabled: false
    maxReplicas: 5
    minReplicas: 1

###############################################################################
#  ____  _     _
# |  _ \(_)___| | _____
# | | | | / __| |/ / __|
# | |_| | \__ \   <\__ \
# |____/|_|___/_|\_\___/
###############################################################################
diskErrorPolicy: "report"
disks:
  - name: harddrive
    type: disk
    bus: virtio
    bootorder: 2
    readonly: false
    pvsize: 16Gi
    pvstorageClassName: fast-raid
    pvaccessMode: ReadWriteOnce
    nodePlacement: scremlin
    source: url
    url: "https://cloud.debian.org/images/cloud/trixie/20251006-2257/debian-13-generic-amd64-20251006-2257.qcow2"

################################################################################
#  _   _      _                      _    ____        _
# | \ | | ___| |___      _____  _ __| | _|  _ \  __ _| |_ __ _
# |  \| |/ _ \ __\ \ /\ / / _ \| '__| |/ / | | |/ _` | __/ _` |
# | |\  |  __/ |_ \ V  V / (_) | |  |   <| |_| | (_| | || (_| |
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\____/ \__,_|\__\__,_|
################################################################################
userDataSecret:
  enabled: false
  name: ""

################################################################################
#   ____ _                 _ ___       _ _
#  / ___| | ___  _   _  __| |_ _|_ __ (_) |_
# | |   | |/ _ \| | | |/ _` || || '_ \| | __|
# | |___| | (_) | |_| | (_| || || | | | | |_
#  \____|_|\___/ \__,_|\__,_|___|_| |_|_|\__|
################################################################################cloudinit:
cloudinit:
  enabled: true
  secret_name: "friend-desktop-user-data"
  image: deserializeme/kv-cloud-init:v0.0.2
  serviceAccount:
    create: true
    name: "friend-desktop-sa"
    existingServiceAccountName: ""
  existingConfigMap: false
  envsubst: true
  extraEnvVars:
    - name: USERNAME
      value: friend
    # Create a password to use with VNC
    # kubectl create secret generic vnc-password --from-literal=password=$(petname --words 3)
    - name: VNC_PASS
      valueFrom:
        secretKeyRef:
          name: "vnc-password"
          key: "password"
  hostname: desktop
  namespace: default
  disable_root: false
  debug: false
  salt: "saltsaltlettuce"
  network:
    config: disabled
  wireguard: []
  users:
    - name: $USERNAME
      groups: users, admin, docker, sudo, kvm
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      lock_passwd: false
      password:
        random: true
      ssh_import_id: []
      ssh_authorized_keys: []
  ca_certs: []
  boot_cmd: []
  write_files: []
  package_reboot_if_required: false
  package_update: true
  package_upgrade: false
  packages:
    - gpg
  runcmd:
    - sudo chown -R $USERNAME:$USERNAME /home/$USERNAME
    ######################
    # Install Docker
    - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - sudo apt-get update
    - sudo apt-get install -y docker-ce
    #####################
    # Run desktop
    - docker run -d --restart always --tmpfs /dev/shm:rw -p 8888:8888 -e PASSWD="$VNC_PASS" deserializeme/debian-xfce
    - echo "done"

################################################################################
# ____                  _             ___     ___
#/ ___|  ___ _ ____   _(_) ___ ___   ( _ )   |_ _|_ __   __ _ _ __ ___  ___ ___
#\___ \ / _ \ '__\ \ / / |/ __/ _ \  / _ \/\  | || '_ \ / _` | '__/ _ \/ __/ __|
# ___) |  __/ |   \ V /| | (_|  __/ | (_>  <  | || | | | (_| | | |  __/\__ \__ \
#|____/ \___|_|    \_/ |_|\___\___|  \___/\/ |___|_| |_|\__, |_|  \___||___/___/
#                                                       |___/
################################################################################
service:
  - name: "desktop-service"
    type: NodePort
    externalTrafficPolicy: Cluster
    ports:
      - name: ssh
        port: 22
        targetPort: 22
        protocol: TCP
      - name: novnc
        port: 8888
        targetPort: 8888
        protocol: TCP
ingress:
  enabled: false
  className: "nginx"
  hostname: "friend-desktop.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "http-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  tls:
    enabled: true
    secretName: "tls-friend-desktop"
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "desktop-service"
            port:
              number: 8888

################################################################################
#  _   _      _                      _      ____       _ _      _
# | \ | | ___| |___      _____  _ __| | __ |  _ \ ___ | (_) ___(_) ___  ___
# |  \| |/ _ \ __\ \ /\ / / _ \| '__| |/ / | |_) / _ \| | |/ __| |/ _ \/ __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <  |  __/ (_) | | | (__| |  __/\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\ |_|   \___/|_|_|\___|_|\___||___/
################################################################################
networkPolicy:
  enabled: true
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          # Exclude traffic to Kubernetes service IPs and pods
          except:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: "ingress-nginx"
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: "ingress-nginx"

################################################################################
#  ____            _
# |  _ \ _ __ ___ | |__   ___  ___
# | |_) | '__/ _ \| '_ \ / _ \/ __|
# |  __/| | | (_) | |_) |  __/\__ \
# |_|   |_|  \___/|_.__/ \___||___/
################################################################################
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  tcpSocket:
    port: 8888
  timeoutSeconds: 10

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 30
  successThreshold: 1
  httpGet:
    port: 8888
