---
# Source: kubevirt-vm/templates/datavolume.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: windows10-base-empty-cert
  namespace: windows10
data:
  ca.pem: ""
---
# Source: kubevirt-vm/templates/datavolume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-system
  namespace: windows10
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
---
# Source: kubevirt-vm/templates/datavolume.yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: installer-iso
  namespace: windows10
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    pvc:
      namespace: windows10
      name: windows-installer
  pvc:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
---
# Source: kubevirt-vm/templates/virtualmachine.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
    metallb-service: windows10-base
  namespace: windows10
  name: windows10-base
spec:
  runStrategy: Once
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: windows10-base
        kubevirt-service: windows10-base
        kubevirt-manager.io/managed: "true"
    spec:
      architecture: amd64
      domain:
        machine:
          type: q35
        clock:
          utc: {}

          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
            kvm: {}
        features:
          kvm: {}
          acpi: {}
          hyperv:
            relaxed: {}
            vapic: {}
            vpindex: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
              direct: {}
            tlbflush: {}
            frequencies: {}
            reenlightenment: {}
            ipi: {}
            runtime: {}
            reset: {}
        cpu:
          dedicatedCpuPlacement: true
          model: host-passthrough
          sockets: 1
          cores: 4
          threads: 1
        memory:
          guest: 8Gi

        firmware:
          bootloader: {}
        devices:
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          autoattachPodInterface: true
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          inputs:
          - type: tablet
            bus: virtio
            name: tablet1
          disks:
          - name: installer-iso
            cdrom:
              bus: sata
              readonly: true
            bootOrder: 1
            errorPolicy: report
          - name: windows-system
            disk:
              bus: virtio
            bootOrder: 2
            errorPolicy: report
          - name: windows-guest-tools
            cdrom:
              bus: sata
              readonly: true
            bootOrder: 3
            errorPolicy: report
        resources:
          requests:
            memory: "8Gi"
          limits:
            memory: "8Gi"
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      priorityClassName: system-node-critical
      volumes:
        - name: installer-iso
          persistentVolumeClaim:
            claimName: installer-iso
        - name: windows-system
          persistentVolumeClaim:
            claimName: windows-system
        - containerDisk:
            image: quay.io/kubevirt/virtio-container-disk:v1.6.2
          name: windows-guest-tools
