{{- if not .Values.virtualMachine.capiMachineTemplate.enabled }}
{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-policy
  namespace: {{ .Values.virtualMachine.namespace }}
spec:
  podSelector:
    matchLabels:
      kubevirt-service: {{ .Values.virtualMachine.name }}
      kubevirt.io: virt-launcher
      kubevirt.io/domain: {{ .Values.virtualMachine.name }}
  policyTypes:
  - Egress
  {{- with .Values.networkPolicy.egress }}
  egress:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-policy
  namespace: {{ .Values.virtualMachine.namespace }}
spec:
  podSelector:
    matchLabels:
      kubevirt-service: {{ .Values.virtualMachine.name }}
      kubevirt.io: virt-launcher
      kubevirt.io/domain: {{ .Values.virtualMachine.name }}
  policyTypes:
    - Ingress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
