{{- if not .Values.virtualMachine.capiMachineTemplate.enabled }}
{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-policy
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  podSelector: {}
  policyTypes:
  - Egress
  {{- with .Values.networkPolicy.egress }}
  egress:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-policy
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
