---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cdi.kubevirt.io: cdi-operator
    name: cdi-operator
    operator.cdi.kubevirt.io: ""
    prometheus.cdi.kubevirt.io: "true"
  name: cdi-operator
  namespace: cdi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
      labels:
        cdi.kubevirt.io: cdi-operator
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
        prometheus.cdi.kubevirt.io: "true"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: cdi.kubevirt.io
                      operator: In
                      values:
                        - cdi-operator
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - env:
            - name: DEPLOY_CLUSTER_RESOURCES
              value: "true"
            - name: OPERATOR_VERSION
              value: v1.63.0
            - name: CONTROLLER_IMAGE
              value: quay.io/kubevirt/cdi-controller:{{ .Chart.AppVersion }}
            - name: IMPORTER_IMAGE
              value: quay.io/kubevirt/cdi-importer:{{ .Chart.AppVersion }}
            - name: CLONER_IMAGE
              value: quay.io/kubevirt/cdi-cloner:{{ .Chart.AppVersion }}
            - name: OVIRT_POPULATOR_IMAGE
              value: quay.io/kubevirt/cdi-importer:{{ .Chart.AppVersion }}
            - name: APISERVER_IMAGE
              value: quay.io/kubevirt/cdi-apiserver:{{ .Chart.AppVersion }}
            - name: UPLOAD_SERVER_IMAGE
              value: quay.io/kubevirt/cdi-uploadserver:{{ .Chart.AppVersion }}
            - name: UPLOAD_PROXY_IMAGE
              value: quay.io/kubevirt/cdi-uploadproxy:{{ .Chart.AppVersion }}
            - name: VERBOSITY
              value: "1"
            - name: PULL_POLICY
              value: IfNotPresent
            - name: MONITORING_NAMESPACE
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: cdi-operator
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.service.name }}
              protocol: {{ .Values.service.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
