apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  name: capi-operator-selfsigned-issuer
  namespace: capi-operator-system
spec:
  selfSigned: {}
