---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  name: capi-operator-manager-role
  namespace: capi-operator-system
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
