{{- if eq .Values.serviceAccount.create true}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.secret_name }}-secret-admin
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name}}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.secret_name }}-secret-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
