{{ if eq .Values.existingConfigMap false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: optimizer-script
  namespace: {{ .Values.namespace }}
data:
  optimize.sh: |
    {{ .Files.Get "scripts/optimize.sh" | nindent 4}}
{{- end }}
