---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  monitorNamespace: {{ .Values.monitorNamespace }}
  monitorAccount: {{ .Values.monitorAccount }}
  configuration:
    {{- with .Values.migrations }}
    migrations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    permittedHostDevices:
      {{- if .Values.permittedHostDevices.pciHostDevices }}
      {{- with .Values.permittedHostDevices.pciHostDevices }}
      pciHostDevices:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      pciHostDevices: []
      {{- end }}
      {{- if .Values.permittedHostDevices.mediatedDevices }}
      {{- with .Values.permittedHostDevices.mediatedDevices }}
      mediatedDevices:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      mediatedDevices: []
      {{- end }}
    {{- if .Values.mediatedDevicesTypes }}
    mediatedDevicesConfiguration:
      {{- with .Values.mediatedDevicesTypes}}
      mediatedDevicesTypes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    apiConfiguration:
      restClient:
        rateLimiter:
          tokenBucketRateLimiter:
            burst: {{ .Values.rateLimits.api.burst }}
            qps: {{ .Values.rateLimits.api.qps }}
    controllerConfiguration:
      restClient:
        rateLimiter:
          tokenBucketRateLimiter:
            burst: {{ .Values.rateLimits.controller.burst }}
            qps: {{ .Values.rateLimits.controller.qps }}
    handlerConfiguration:
      restClient:
        rateLimiter:
          tokenBucketRateLimiter:
            burst: {{ .Values.rateLimits.handler.burst }}
            qps: {{ .Values.rateLimits.handler.qps }}
    webhookConfiguration:
      restClient:
        rateLimiter:
          tokenBucketRateLimiter:
            burst: {{ .Values.rateLimits.webhook.burst }}
            qps: {{ .Values.rateLimits.webhook.qps }}
    developerConfiguration:
      useEmulation: {{ .Values.useEmulation }}
      {{- with .Values.featureGates }}
      featureGates:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
