---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: capi-control-plane
  namespace: {{ .Values.cluster.namespace }}
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: {{ .Values.cluster.namespace }}
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                resources:
                  requests:
                    ephemeral-storage: {{ .Values.MachineTemplates.controlPlane.disk }}
                cpu:
                  model: {{ .Values.MachineTemplates.controlPlane.cpuModel }}
                  cores: {{ .Values.MachineTemplates.controlPlane.cores }}
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
                    - name: emptydisk
                      disk:
                        bus: virtio
                  networkInterfaceMultiqueue: true
                memory:
                  guest: {{ .Values.MachineTemplates.controlPlane.memory }}
              evictionStrategy: External
              volumes:
                - containerDisk:
                    image: quay.io/capk/ubuntu-2204-container-disk:{{ .Values.cluster.version }}
                  name: containervolume
                - name: emptydisk
                  emptyDisk:
                    capacity: 8Gi
