{{- if eq .Values.cluster.provider "k3s" }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KThreesConfigTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: {{ .Values.cluster.namespace }}
spec:
  template:
    spec:
      {{- if .Values.cluster.kubeletConfigFile.enabled }}
      files:
      {{- $content := .Values.cluster.kubeletConfigFile.content }}
        - path: /etc/kubernetes/kubelet.yaml
          permissions: "0640"
          content: |-
            {{- $content | nindent 12 }}
        {{- end }}
      {{- with .Values.cluster.preCommands }}
      preK3sCommands:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.cluster.postCommands }}
      postK3sCommands:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      serverConfig: {}
      agentConfig: {}
      #  kubeProxyArgs: []
      #  kubeletArgs: []
      #  nodeLabels: []
      #  nodeName: ""
      #  nodeTaints: []
      #  privateRegistry: ""
{{- end }}
