{{- if eq .Values.cluster.provider "k3s" }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KThreesControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
spec:
  kthreesConfigSpec:
    {{- if gt (len .Values.cluster.extraFiles.controlPlane ) 0 }}
    files:
    {{- range $key, $value := .Values.cluster.extraFiles.controlPlane }}
      - path: {{ $value.path }}
        owner: {{ $value.owner }}
        content: |
          {{- $value.content | nindent 10}}
    {{- end }}
    {{- end }}
    {{- with .Values.cluster.preCommands }}
    preK3sCommands:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cluster.postCommands }}
    postK3sCommands:
      {{- toYaml . | nindent 6 }}
    {{- end}}
    serverConfig:
      disableCloudController: {{ .Values.cluster.disableCloudController }}
      kubeAPIServerArg:
        - --anonymous-auth=true
      {{- with .Values.cluster.tlsSan }}
      tlsSan:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.cluster.advertiseAddress }}
      advertiseAddress: {{ .Values.cluster.advertiseAddress }}
      {{- end }}
      {{- if .Values.cluster.advertisePort }}
      advertisePort: {{ .Values.cluster.advertisePort | quote }}
      {{- end }}
      clusterCidr: {{ .Values.cluster.podCidrBlock }}
      serviceCidr: {{ .Values.cluster.serviceCidrBlock }}
      clusterDomain: {{ .Values.cluster.dnsDomain }}
      cloudProviderName: {{ .Values.cluster.cloudProviderName }}
      {{- with .Values.cluster.disableComponents }}
      disableComponents:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    agentConfig:
      {{- with .Values.cluster.kubeletArgs }}
      kubeletArgs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      privateRegistry: ""
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: "{{ .Values.cluster.name }}-control-plane"
  replicas: {{ .Values.controlPlane.size }}
  version: {{ .Values.cluster.version }}
{{- end }}
