{{- if eq .Values.cluster.provider "k3s" }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KThreesConfigTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: {{ .Values.cluster.namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
spec:
  template:
    spec:
      {{- if gt (len .Values.cluster.extraFiles.worker ) 0 }}
      files:
      {{- range $key, $value := .Values.cluster.extraFiles.worker }}
        - path: {{ $value.path }}
          owner: {{ $value.owner }}
          content: |
            {{- $value.content | nindent 12 }}
      {{- end }}
      {{- end }}
      {{- with .Values.cluster.preCommands }}
      preK3sCommands:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.cluster.postCommands }}
      postK3sCommands:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      agentConfig:
        {{- with .Values.cluster.kubeletArgs }}
        kubeletArgs:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        privateRegistry: ""
{{- end }}
