---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  controlPlaneServiceTemplate:
    metadata:
      namespace: {{ .Values.cluster.namespace }}
      {{- range $key, $value := .Values.cluster.controlPlaneService.annotations }}
      annotations:
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      type: {{ .Values.cluster.controlPlaneService.type }}
