{{- if eq .Values.provider "kubeadm" }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
  {{- if eq .Values.cluster.disableKubePorxy true }}
  annotations:
    controlplane.cluster.x-k8s.io/skip-kube-proxy: "true"
  {{- end }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      networking:
        dnsDomain: {{ .Values.cluster.dnsDomain }}
        podSubnet: {{ .Values.cluster.podCidrBlock }}
        serviceSubnet: {{ .Values.cluster.serviceCidrBlock }}
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        {{- if eq .Values.cluster.disableKubePorxy true }}
        skipPhases:
        - "addon/kube-proxy"
        {{- end }}
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: {{ .Values.cluster.name }}-control-plane
      namespace: {{ .Values.cluster.namespace }}
  replicas: {{ .Values.MachineTemplates.controlPlane.size }}
  version: {{ .Values.cluster.version }}
{{- end }}
